/**
 * Regenerates `src/generators/generated-index.ts`: a static-import module
 * listing every file under `src/generators/<aine>/kursus-NN/`, in the same
 * shape the registry's old runtime filesystem scan used to walk.
 *
 * Static imports (not a runtime `fs` scan + dynamic `import()`) are what
 * let Next.js's bundler actually include these generator files in the
 * server bundle — see the long comment on `discoverGenerators` in
 * `src/generators/registry.ts` for why the runtime version breaks inside
 * Next.js specifically. Re-run automatically before `dev`/`build`/`check`
 * (see package.json) — never edit the generated file by hand.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import {
  COURSE_DIR_PATTERN,
  DEFAULT_ROOT,
  listDirs,
  listGeneratorFiles,
} from "../src/generators/registry";

const OUTPUT_FILE = path.join(DEFAULT_ROOT, "generated-index.ts");

function findModulePaths(): string[] {
  const modulePaths: string[] = [];
  for (const aine of listDirs(DEFAULT_ROOT)) {
    const aineDir = path.join(DEFAULT_ROOT, aine);
    for (const kursusDir of listDirs(aineDir).filter((name) =>
      COURSE_DIR_PATTERN.test(name),
    )) {
      const kursusPath = path.join(aineDir, kursusDir);
      for (const file of listGeneratorFiles(kursusPath)) {
        modulePaths.push(`./${aine}/${kursusDir}/${file.replace(/\.tsx?$/, "")}`);
      }
    }
  }
  return modulePaths;
}

function render(modulePaths: string[]): string {
  const imports = modulePaths.map((p, i) => `import * as m${i} from "${p}";`);
  const entries = modulePaths.map((_, i) => `  m${i},`);

  return [
    "// AUTO-GENERATED by scripts/generate-registry-index.ts — do not edit by hand.",
    "// Regenerated before every dev/build/check (see package.json).",
    "",
    ...imports,
    "",
    "export const GENERATOR_MODULES: Record<string, unknown>[] = [",
    ...entries,
    "];",
    "",
  ].join("\n");
}

const modulePaths = findModulePaths();
writeFileSync(OUTPUT_FILE, render(modulePaths));
console.log(
  `generated ${path.relative(process.cwd(), OUTPUT_FILE)} with ${modulePaths.length} module(s)`,
);
